/-
  VeriTrialExport.lean — Self-contained N-state export of the VeriTrial model.

  Generated by `VeriTrial/scripts/export_pbpk_to_qed.py` (`emit_lean_export`)
  from the symbolic Jacobian of the live model. References only QED's
  domain-agnostic `Compartmental` engine. No `sorry` or `sorryAx`.
-/

import Compartmental

open Compartmental

/-- AST-extracted N x N Jacobian symbolically differentiated from the model ODE. -/
noncomputable def extracted_matrix (ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL : ℝ) :
    Fin 6 → Fin 6 → ℝ := fun i j =>
    if i.val = 0 ∧ j.val = 0 then (-ka)
  else   if i.val = 1 ∧ j.val = 1 then (-Ql/(Kpl*Vl))
  else   if i.val = 1 ∧ j.val = 2 then (Ql/Vc)
  else   if i.val = 2 ∧ j.val = 0 then (ka)
  else   if i.val = 2 ∧ j.val = 1 then (Ql/(Kpl*Vl))
  else   if i.val = 2 ∧ j.val = 2 then ((-CL - Qe - Ql - Qp)/Vc)
  else   if i.val = 2 ∧ j.val = 3 then (Qp/(Kpp*Vp))
  else   if i.val = 2 ∧ j.val = 4 then (Qe/(Kpe*Ve))
  else   if i.val = 3 ∧ j.val = 2 then (Qp/Vc)
  else   if i.val = 3 ∧ j.val = 3 then (-Qp/(Kpp*Vp))
  else   if i.val = 4 ∧ j.val = 2 then (Qe/Vc)
  else   if i.val = 4 ∧ j.val = 4 then (-Qe/(Kpe*Ve))
  else   if i.val = 5 ∧ j.val = 2 then (CL/Vc)
  else 0

/-- Off-diagonal entries of the extracted matrix are non-negative. -/
theorem extracted_offDiag_nonneg
  (ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL : ℝ)
  (hka : 0 < ka) (hQl : 0 < Ql) (hQp : 0 < Qp) (hQe : 0 < Qe)
  (hVc : 0 < Vc) (hVl : 0 < Vl) (hVp : 0 < Vp) (hVe : 0 < Ve)
  (hKpl : 0 < Kpl) (hKpp : 0 < Kpp) (hKpe : 0 < Kpe)
  (hCL : 0 ≤ CL)
  (i j : Fin 6) (hij : i ≠ j) :
  0 ≤ extracted_matrix ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL i j := by
  fin_cases i <;> fin_cases j <;> simp_all [extracted_matrix] <;> positivity

/-- Every column sum of the extracted matrix vanishes exactly. -/
theorem extracted_colSum_eq_zero
  (ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL : ℝ)
  (hVc : 0 < Vc) (hVl : 0 < Vl) (hVp : 0 < Vp) (hVe : 0 < Ve)
  (hKpl : 0 < Kpl) (hKpp : 0 < Kpp) (hKpe : 0 < Kpe)
  (j : Fin 6) :
  ∑ i, extracted_matrix ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL i j = 0 := by
  have hVc0 : Vc ≠ 0 := ne_of_gt hVc
  have hVl0 : Vl ≠ 0 := ne_of_gt hVl
  have hVp0 : Vp ≠ 0 := ne_of_gt hVp
  have hVe0 : Ve ≠ 0 := ne_of_gt hVe
  have hKpl0 : Kpl ≠ 0 := ne_of_gt hKpl
  have hKpp0 : Kpp ≠ 0 := ne_of_gt hKpp
  have hKpe0 : Kpe ≠ 0 := ne_of_gt hKpe
  fin_cases j <;>
    rw [Finset.sum_fin_eq_sum_range] <;>
    simp [extracted_matrix, Finset.sum_range_succ] <;>
    field_simp <;> ring

/-- Every column sum of the extracted matrix is non-positive. -/
theorem extracted_colSum_nonpos
  (ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL : ℝ)
  (hVc : 0 < Vc) (hVl : 0 < Vl) (hVp : 0 < Vp) (hVe : 0 < Ve)
  (hKpl : 0 < Kpl) (hKpp : 0 < Kpp) (hKpe : 0 < Kpe)
  (j : Fin 6) :
  ∑ i, extracted_matrix ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL i j ≤ 0 := by
  rw [extracted_colSum_eq_zero ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL
    hVc hVl hVp hVe hKpl hKpp hKpe j]

/-- The extracted model inhabits QED's abstract compartmental type. -/
noncomputable def veritrial_compartmental
  (ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL : ℝ)
  (hka : 0 < ka) (hQl : 0 < Ql) (hQp : 0 < Qp) (hQe : 0 < Qe)
  (hVc : 0 < Vc) (hVl : 0 < Vl) (hVp : 0 < Vp) (hVe : 0 < Ve)
  (hKpl : 0 < Kpl) (hKpp : 0 < Kpp) (hKpe : 0 < Kpe)
  (hCL : 0 ≤ CL) :
  CompartmentalMatrix (Fin 6) where
  toFun := extracted_matrix ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL
  offDiag_nonneg :=
    extracted_offDiag_nonneg ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL
      hka hQl hQp hQe hVc hVl hVp hVe hKpl hKpp hKpe hCL
  colSums_nonpos :=
    extracted_colSum_nonpos ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL
      hVc hVl hVp hVe hKpl hKpp hKpe

/-- Mass dissipation over the extracted matrix: transport of QED's generic
    `mass_dissipation_rate` certificate onto the AST-extracted model. -/
theorem veritrial_mass_dissipation
  (ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL : ℝ)
  (hka : 0 < ka) (hQl : 0 < Ql) (hQp : 0 < Qp) (hQe : 0 < Qe)
  (hVc : 0 < Vc) (hVl : 0 < Vl) (hVp : 0 < Vp) (hVe : 0 < Ve)
  (hKpl : 0 < Kpl) (hKpp : 0 < Kpp) (hKpe : 0 < Kpe)
  (hCL : 0 ≤ CL)
  {y : Fin 6 → ℝ} (hy : NonNegVec y) :
  totalMass (mulVec (extracted_matrix ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL) y) ≤ 0 := by
  exact mass_dissipation_rate
    (veritrial_compartmental ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL
      hka hQl hQp hQe hVc hVl hVp hVe hKpl hKpp hKpe hCL).isMetzler
    (veritrial_compartmental ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL
      hka hQl hQp hQe hVc hVl hVp hVe hKpl hKpp hKpe hCL).hasNonposColSums
    hy

/-- Unified extension matrix: the top-left block is the extracted model. -/
noncomputable def extracted_dili_matrix (ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL
    k_synth k_deplete IC50 k_leak k_elim ALT_base : ℝ) :
    Fin 9 → Fin 9 → ℝ := fun i j =>
  if h : i.val < 6 ∧ j.val < 6 then
    extracted_matrix ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL ⟨i.val, by omega⟩ ⟨j.val, by omega⟩
  else 0

/-- The top-left block of the unified matrix is the extracted model. -/
theorem veritrial_dili_block
  (ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL
    k_synth k_deplete IC50 k_leak k_elim ALT_base : ℝ)
  (i j : Fin 6) :
  extracted_dili_matrix ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL
      k_synth k_deplete IC50 k_leak k_elim ALT_base
      ⟨i.val, by omega⟩ ⟨j.val, by omega⟩
    = extracted_matrix ka Ql Qp Qe Vc Vl Vp Ve Kpl Kpp Kpe CL i j := by
  unfold extracted_dili_matrix
  split_ifs with h
  · rfl
  · exact absurd ⟨i.isLt, j.isLt⟩ h
